### ISSUE TITLE
Change logout process

### ISSUE THREAD

**Issue by yujingaya** [sparcs-kaist/new-ara-web#20]
- [ ] /api/users/<pk>/sso_logout_url/ 을 호출해서 sso_logout_url을 확보
- [ ] /rest-auth/logout/ api를 호출
- [x] JWT 삭제
- [ ] Sparcs SSO에서도 로그아웃 하고 싶으면 sso_logout_url로 이동하라고 유저에게 알려주기(모달?)

**Comment by talkwithraon** [comment]
다른 티켓 들에 비해 우선순위가 상당히 낮음을 기억해주세요. JWT 삭제만으로도 문제 없이 작동합니다!

**Comment by jwoo0122** [comment]
- [ ] Auto logout for JWT error (401)

**Comment by jwoo0122** [comment]
Change Auth logic *without JWT.*

- [ ] no more "/user_profiles/{int}", use "/me".
- [ ] remove all jwt related logics, include darkmode.

**Comment by apple12347678** [comment]
vuex로 상태 관리를 하고 있는 상황에서 jwt의 페이로드가 무의미하다고 판단되어 jwt 로직을 전부 제거하려 합니다. 백엔드의 jwt 생성 라이브러리 등이 상당히 노후화되어 이상한 출력값을 내놓기 때문도 있습니다.

**Comment by apple12347678** [comment]
다른 사람의 프로필을 조회할 로직이 필요할 수 있으므로 일단 /user_profiles/{int}는 살려두겠습니다.

**Comment by jwoo0122** [comment]
추가된 내용은 #60 으로 이동했습니다.
