### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by YujinGaya** [sparcs-kaist/new-ara-web#24]
- [x] CSS for mobile
- [ ] Handle request for desktop site
- [ ] Maybe [pwa](https://developers.google.com/web/progressive-web-apps/)..?

**Comment by YujinGaya** [comment]
Found that `Request for desktop site` feature in Chrome is essentially a [user agent spoofing](https://productforums.google.com/forum/#!topic/chrome/tz24aCo6F3I). Since we don't respond to user agent, we can't support the feature.

If we should support this, we may consider [this link](https://css-tricks.com/user-opt-out-responsive-design/).

But for now, I won't implement this until somebody requests it.

**Comment by jwoo0122** [comment]
No PWA support yet.
