### ISSUE TITLE
File attachment

### ISSUE THREAD

**Issue by YujinGaya** [sparcs-kaist/new-ara-web#4]
File attachment in Write.vue

- [x] Can attach file in post
- [ ] Can download file from the post
- [ ] Can edit file list when editing the post

**Comment by YujinGaya** [comment]
You may consult [this snippet](https://github.com/sparcs-kaist/new-ara-web/blob/c8cd0886c701f0f0da94eaa896c11df0fe8c4286/src/api/user.js#L8)

**Comment by jwoo0122** [comment]
파일의 전송 자체는 가능하나, 이를 불러오는 코드가 제대로 짜여있지 않은 것으로 보임.

**Comment by jwoo0122** [comment]
Cannot send file, there is no implement for binary file transport. Need to use form data to send image to API server, but I can't find any code about that.
