### ISSUE TITLE
Post doesn't work with Link.

### ISSUE THREAD

**Issue by jwoo0122** [sparcs-kaist/new-ara-web#62]

**Comment by jwoo0122** [comment]
Django 를 거치는 과정에서, url 을 잡아내면 자동으로 a 태그로 파싱하는 것으로 보임.

**Comment by jwoo0122** [comment]
@apple12347678 이거 확인하시고 혹시 해당 기능 끌 수 있다면 말씀해 주세요. 아무래도 Django 에서 컨텐츠에 어떤 변형을 가하는 일 자체가 없어야 할 것 같습니다. Tiptap 스스로 정한 룰 그대로, 데이터가 DB 에 반영될 수 있도록 Django 의 모든 자동 파싱 기능을 꺼야 한다고 생각되네요.

**Comment by apple12347678** [comment]
@jwoo0122 찾아볼게요 그런데 tiptap의 룰을 그대로 따라가는건 상당히 위험해 보입니다. production 전에는 tiptap이 준 json 필드들을 순회하면서 sanitizing하는 기능은 반드시 필요할 것 같아요. tiptap으로만 POST를 보내는게 아니니까...

**Comment by jwoo0122** [comment]
그러면 tiptap json 구조를 파악해서 해당 룰에 맞는 컨텐츠만 수용해야겠네요.
