### ISSUE TITLE
Inline image import

### ISSUE THREAD

**Issue by jwoo0122** [sparcs-kaist/new-ara-web#64]
- [x] Enable inline photo insert
- [x] Enable photo import by url (markdown)

**Comment by jwoo0122** [comment]
Tiptap does not support image embed, but only image insert by url. We need to find another editor library for embed image, or implement it by self.

**Comment by apple12347678** [comment]
@jwoo0122 이미지 업로드(업로드 중에 스피너) -> url acquire -> 인라인 삽입 가능한가요? POST /api/attachment는 POST api/article과 별개로 동작하는 걸로 암. 만약 이미지가 다수면 DB 모델에도 약간의 변경 필요해보임.

**Comment by jwoo0122** [comment]
> @jwoo0122 이미지 업로드(업로드 중에 스피너) -> url acquire -> 인라인 삽입 가능한가요? POST /api/attachment는 POST api/article과 별개로 동작하는 걸로 암. 만약 이미지가 다수면 DB 모델에도 약간의 변경 필요해보임.

그렇게 생각하니 인라인 이미지는 어느정도는 가능하겠네요. 다만 url 을 일반 스트링이랑 어떻게 구분해서 html 로 넣을지는 좀 더 생각해봐야 됩니다. back 에서 sanitizing 을 해버리면 프론트에서 링크를 넣어도 의미가 없어지니까, 양측이 합의한 새로운 문법을 쓴다던가...

**Comment by HelloWorld017** [comment]
+ 아 일단 사실은 편집 중에 blob url로 메모리에 있는 이미지를 띄우고 포스트 작성 시에 한번에 업로드 시키는 방법을 썼긴 합니다.

**Comment by jwoo0122** [comment]
> +아 참고로 일단 사실은 편집 중에 blob url로 메모리에 있는 이미지를 띄우고 포스트 작성 시에 한번에 업로드 시키는 방법을 썼긴 합니다.

?? 이미 작업 하셨나요??

**Comment by HelloWorld017** [comment]
그 issue-64 브랜치에서 작업했고 내일중으로 풀리퀘 올릴 예정이에요!

**Comment by HelloWorld017** [comment]
앗 혹시 설마 작업하시고 계시던 거 있었나요?ㅠㅠㅠ

**Comment by jwoo0122** [comment]
> 앗 혹시 설마 작업하시고 계시던 거 있었나요?ㅠㅠㅠ

아뇨아뇨 이 티켓이랑 관련해서는 작업하던거 딱히 없었습니당 편하게 작업하셔도 돼요! 제가 작업하는 것들은 제 이름으로 assign 걸어두겠습니다

**Comment by HelloWorld017** [comment]
Closed by #100
