### ISSUE TITLE
Tiptap comunicate with HTML, not JSON

### ISSUE THREAD

**Issue by jwoo0122** [sparcs-kaist/new-ara-web#90]
Cause of the problem that It's extremely complicate to sanitizing Tiptap JSON from XSS (in Django), we need to change tiptap to make HTML itself not JSON. And there is no more tiptap readonly mode. React can just render HTML from Django, never considering XSS cause it already sanitized.

**Comment by apple12347678** [comment]
다른 텍스트 필드 (유저명, 글 제목 등)은 전혀 sanitize하지 않을 것(vue에서 걸러야함) 글 내용은 pure HTML로 sanitize 후 저장하여 tiptap의 setHTML(?)을 쓰든, vue버전 dangerouslySetInnerHTML을 쓰든 그대로 나타나기만 하면 됨.
