### ISSUE TITLE
Comment Command + Enter

### ISSUE THREAD

**Issue by jwoo0122** [sparcs-kaist/new-ara-web#95]
- [ ] Missing Last letter in Chrome, macOS
- [ ] Recomment not suppported

**Comment by jwoo0122** [comment]
Maybe it would be cool if the "Make Comment" button is with text like "Make comment (Command + Enter)" or "Make comment ( ⌘ + Enter)" depends on OS.

**Comment by jwoo0122** [comment]
What about just send comment by 'enter' key, and line feed with Shift + enter?

**Comment by HelloWorld017** [comment]
In some cases, just enter might be an annoyance for some portion of users. I think making user to choice what to use is a ideal solution, but as we don't have time it would be hard to implement in 1.1

For now, sending by `enter` and line feed with `shift+enter` might be a good solution, except for mobile device.

+As I don't have Mac OS (I couldn't reproduce the error in windows chrome, might be related with IME?) it would be hard to fix this bug.

**Comment by jwoo0122** [comment]
> +As I don't have Mac OS (I couldn't reproduce the error in windows chrome, might be related with IME?) it would be hard to fix this bug.

Later I'll handle it.
